import 'package:flutter/material.dart';
import '../models/cart_item.dart';
import '../models/product.dart';

class CartService extends ChangeNotifier {
  static const double freeDeliveryThreshold = 499;
  static const double baseDeliveryFee = 29;
  static const double platformFeeAmount = 7;
  static const double handlingFeeAmount = 5;

  final List<CartItem> _items = [];
  String? _appliedCoupon;
  double _couponDiscount = 0;
  double _deliveryTip = 0;

  List<CartItem> get items => List.unmodifiable(_items);
  String? get appliedCoupon => _appliedCoupon;
  double get deliveryTip => _deliveryTip;
  double get platformFee => _items.isEmpty ? 0 : platformFeeAmount;
  double get handlingFee => _items.isEmpty ? 0 : handlingFeeAmount;
  double get couponDiscount => _couponDiscount;
  bool get meetsMinimumOrderRequirement => itemCount >= 3;

  int get itemCount => _items.fold(0, (sum, item) => sum + item.quantity);

  double get totalAmount => _items.fold(0, (sum, item) => sum + item.totalPrice);

  double get deliveryFee => totalAmount >= freeDeliveryThreshold ? 0 : baseDeliveryFee;

  double get grandTotal {
    final total = totalAmount + deliveryFee + platformFee + handlingFee + deliveryTip - couponDiscount;
    return total < 0 ? 0 : total;
  }

  double get savings => _items.fold(0.0, (sum, item) {
        if (item.product.originalPrice != null) {
          return sum +
              (item.product.originalPrice! - item.product.price) * item.quantity;
        }
        return sum;
      });

  double get amountForFreeDelivery =>
      totalAmount >= freeDeliveryThreshold ? 0 : (freeDeliveryThreshold - totalAmount);

  bool isInCart(String productId) {
    return _items.any((item) => item.product.id == productId);
  }

  int getQuantity(String productId) {
    final item = _items.where((item) => item.product.id == productId);
    return item.isEmpty ? 0 : item.first.quantity;
  }

  void addItem(Product product) {
    final existingIndex = _items.indexWhere((item) => item.product.id == product.id);
    if (existingIndex >= 0) {
      _items[existingIndex].quantity++;
    } else {
      _items.add(CartItem(product: product));
    }
    notifyListeners();
  }

  void removeItem(String productId) {
    _items.removeWhere((item) => item.product.id == productId);
    notifyListeners();
  }

  void updateQuantity(String productId, int quantity) {
    final index = _items.indexWhere((item) => item.product.id == productId);
    if (index >= 0) {
      if (quantity <= 0) {
        _items.removeAt(index);
      } else {
        _items[index].quantity = quantity;
      }
      notifyListeners();
    }
  }

  void incrementQuantity(String productId) {
    final index = _items.indexWhere((item) => item.product.id == productId);
    if (index >= 0) {
      _items[index].quantity++;
      notifyListeners();
    }
  }

  void decrementQuantity(String productId) {
    final index = _items.indexWhere((item) => item.product.id == productId);
    if (index >= 0) {
      if (_items[index].quantity > 1) {
        _items[index].quantity--;
      } else {
        _items.removeAt(index);
      }
      notifyListeners();
    }
  }

  void clear() {
    _items.clear();
    _deliveryTip = 0;
    _appliedCoupon = null;
    _couponDiscount = 0;
    notifyListeners();
  }

  void setDeliveryTip(double value) {
    _deliveryTip = value;
    notifyListeners();
  }

  String? applyCoupon(String rawCode) {
    final code = rawCode.trim().toUpperCase();
    if (code.isEmpty) {
      _appliedCoupon = null;
      _couponDiscount = 0;
      notifyListeners();
      return 'Enter a coupon code';
    }
    _appliedCoupon = null;
    _couponDiscount = 0;
    notifyListeners();
    return 'Coupons can only be generated by a store owner or platform admin.';
  }
}
